set(_CATKIN_CURRENT_PACKAGE "roswell_defs")
set(roswell_defs_VERSION "0.2.0")
set(roswell_defs_MAINTAINER "Michael Ferguson <mike@vanadiumlabs.com>")
set(roswell_defs_PACKAGE_FORMAT "1")
set(roswell_defs_BUILD_DEPENDS )
set(roswell_defs_BUILD_EXPORT_DEPENDS "urdf" "xacro" "arbotix_controllers" "diagnostic_aggregator" "etherbotix_python" "openni2_launch" "robot_state_publisher" "urg_node" "joy" "ps3joy")
set(roswell_defs_BUILDTOOL_DEPENDS "catkin")
set(roswell_defs_BUILDTOOL_EXPORT_DEPENDS )
set(roswell_defs_EXEC_DEPENDS "urdf" "xacro" "arbotix_controllers" "diagnostic_aggregator" "etherbotix_python" "openni2_launch" "robot_state_publisher" "urg_node" "joy" "ps3joy")
set(roswell_defs_RUN_DEPENDS "urdf" "xacro" "arbotix_controllers" "diagnostic_aggregator" "etherbotix_python" "openni2_launch" "robot_state_publisher" "urg_node" "joy" "ps3joy")
set(roswell_defs_TEST_DEPENDS )
set(roswell_defs_DOC_DEPENDS )
set(roswell_defs_DEPRECATED "")