set(_CATKIN_CURRENT_PACKAGE "roswell_navigation")
set(roswell_navigation_VERSION "0.2.0")
set(roswell_navigation_MAINTAINER "Michael Ferguson <mike@vanadiumlabs.com>")
set(roswell_navigation_PACKAGE_FORMAT "1")
set(roswell_navigation_BUILD_DEPENDS )
set(roswell_navigation_BUILD_EXPORT_DEPENDS "navigation")
set(roswell_navigation_BUILDTOOL_DEPENDS "catkin")
set(roswell_navigation_BUILDTOOL_EXPORT_DEPENDS )
set(roswell_navigation_EXEC_DEPENDS "navigation")
set(roswell_navigation_RUN_DEPENDS "navigation")
set(roswell_navigation_TEST_DEPENDS )
set(roswell_navigation_DOC_DEPENDS )
set(roswell_navigation_DEPRECATED "")