set(_CATKIN_CURRENT_PACKAGE "roswell_control")
set(roswell_control_VERSION "0.0.0")
set(roswell_control_MAINTAINER "ros <ros@todo.todo>")
set(roswell_control_PACKAGE_FORMAT "1")
set(roswell_control_BUILD_DEPENDS "ros_control" "ros_controllers")
set(roswell_control_BUILD_EXPORT_DEPENDS "ros_control" "ros_controllers")
set(roswell_control_BUILDTOOL_DEPENDS "catkin")
set(roswell_control_BUILDTOOL_EXPORT_DEPENDS )
set(roswell_control_EXEC_DEPENDS "ros_control" "ros_controllers")
set(roswell_control_RUN_DEPENDS "ros_control" "ros_controllers")
set(roswell_control_TEST_DEPENDS )
set(roswell_control_DOC_DEPENDS )
set(roswell_control_DEPRECATED "")