roswell:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  base_l_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_l_wheel_joint
    pid: {p: 83000.0, i: 500.01, d: 100.0}
    # pid: {p: 100.0, i: 0.01, d: 10.0}
  base_r_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_r_wheel_joint
    pid: {p: 83000.0, i: 500.01, d: 100.0}
    # pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_shoulder_pan_controller:
    type: effort_controllers/JointPositionController
    joint: arm_shoulder_pan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_shoulder_lift_controller:
    type: effort_controllers/JointPositionController
    joint: arm_shoulder_lift_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_upperarm_roll_controller:
    type: effort_controllers/JointPositionController
    joint: arm_upperarm_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_wrist_flex_controller:
    type: effort_controllers/JointPositionController
    joint: arm_wrist_flex_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_wrist_roll_controller:
    type: effort_controllers/JointPositionController
    joint: arm_wrist_roll_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  l_gripper_controller:
    type: effort_controllers/JointPositionController
    joint: l_gripper_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  r_gripper_controller:
    type: effort_controllers/JointPositionController
    joint: r_gripper_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  head_pan_controller:
    type: effort_controllers/JointPositionController
    joint: head_pan_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  head_tilt_controller:
    type: effort_controllers/JointPositionController
    joint: head_tilt_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_lift_controller:
    type: effort_controllers/JointPositionController
    joint: arm_lift_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

