set(_CATKIN_CURRENT_PACKAGE "roswell_gazebo")
set(roswell_gazebo_VERSION "0.6.1")
set(roswell_gazebo_MAINTAINER "Michael Ferguson <mferguson@fetchrobotics.com>")
set(roswell_gazebo_PACKAGE_FORMAT "1")
set(roswell_gazebo_BUILD_DEPENDS "angles" "control_toolbox" "gazebo_ros" "robot_controllers" "robot_controllers_interface")
set(roswell_gazebo_BUILD_EXPORT_DEPENDS "actionlib" "control_toolbox" "depth_image_proc" "roswell_description" "gazebo_ros" "geometry_msgs" "image_proc" "nodelet" "robot_controllers" "robot_controllers_interface" "rgbd_launch" "trajectory_msgs" "xacro")
set(roswell_gazebo_BUILDTOOL_DEPENDS "catkin")
set(roswell_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(roswell_gazebo_EXEC_DEPENDS "actionlib" "control_toolbox" "depth_image_proc" "roswell_description" "gazebo_ros" "geometry_msgs" "image_proc" "nodelet" "robot_controllers" "robot_controllers_interface" "rgbd_launch" "trajectory_msgs" "xacro")
set(roswell_gazebo_RUN_DEPENDS "actionlib" "control_toolbox" "depth_image_proc" "roswell_description" "gazebo_ros" "geometry_msgs" "image_proc" "nodelet" "robot_controllers" "robot_controllers_interface" "rgbd_launch" "trajectory_msgs" "xacro")
set(roswell_gazebo_TEST_DEPENDS )
set(roswell_gazebo_DOC_DEPENDS )
set(roswell_gazebo_DEPRECATED "")