set(_CATKIN_CURRENT_PACKAGE "roswell_tb3_sim")
set(roswell_tb3_sim_VERSION "0.1.5")
set(roswell_tb3_sim_MAINTAINER "Pyo <pyo@robotis.com>")
set(roswell_tb3_sim_PACKAGE_FORMAT "1")
set(roswell_tb3_sim_BUILD_DEPENDS "nav_msgs" "roscpp" "std_msgs" "sensor_msgs" "geometry_msgs" "tf" "gazebo_ros")
set(roswell_tb3_sim_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "std_msgs" "sensor_msgs" "geometry_msgs" "tf" "gazebo_ros")
set(roswell_tb3_sim_BUILDTOOL_DEPENDS "catkin")
set(roswell_tb3_sim_BUILDTOOL_EXPORT_DEPENDS )
set(roswell_tb3_sim_EXEC_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "std_msgs" "sensor_msgs" "geometry_msgs" "tf" "gazebo_ros")
set(roswell_tb3_sim_RUN_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "std_msgs" "sensor_msgs" "tf" "gazebo_ros")
set(roswell_tb3_sim_TEST_DEPENDS )
set(roswell_tb3_sim_DOC_DEPENDS )
set(roswell_tb3_sim_DEPRECATED "")