set(_CATKIN_CURRENT_PACKAGE "roswell_moveit_config")
set(roswell_moveit_config_VERSION "0.2.0")
set(roswell_moveit_config_MAINTAINER "MoveIt Setup Assistant <assistant@moveit.ros.org>")
set(roswell_moveit_config_PACKAGE_FORMAT "1")
set(roswell_moveit_config_BUILD_DEPENDS "roswell_defs")
set(roswell_moveit_config_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "roswell_defs")
set(roswell_moveit_config_BUILDTOOL_DEPENDS "catkin")
set(roswell_moveit_config_BUILDTOOL_EXPORT_DEPENDS )
set(roswell_moveit_config_EXEC_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "roswell_defs")
set(roswell_moveit_config_RUN_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "roswell_defs")
set(roswell_moveit_config_TEST_DEPENDS )
set(roswell_moveit_config_DOC_DEPENDS )
set(roswell_moveit_config_DEPRECATED "")