# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_elbow_flex_joint:
    has_velocity_limits: true
    max_velocity: 0.524
  arm_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.0508
    has_position_limits: true
    min_position: -0.591
    max_position: 0.0
    has_effort_limits: true
    max_effort: 450
  arm_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.524
    max_acceleration: 0
  arm_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 0.524
    max_acceleration: 0
  arm_upperarm_roll_joint:
    has_velocity_limits: true
    max_velocity: 0.524
    max_acceleration: 0
  arm_wrist_flex_joint:
    has_velocity_limits: true
    max_acceleration: 0
  arm_wrist_roll_joint:
    has_velocity_limits: true
    max_acceleration: 0
  l_gripper_joint:
    has_velocity_limits: true
    max_acceleration: 0
  r_gripper_joint:
    has_velocity_limits: true
    max_acceleration: 0
