set(_CATKIN_CURRENT_PACKAGE "roswell_gazebo_demo")
set(roswell_gazebo_demo_VERSION "0.6.1")
set(roswell_gazebo_demo_MAINTAINER "Michael Ferguson <mferguson@fetchrobotics.com>")
set(roswell_gazebo_demo_PACKAGE_FORMAT "1")
set(roswell_gazebo_demo_BUILD_DEPENDS )
set(roswell_gazebo_demo_BUILD_EXPORT_DEPENDS "actionlib" "roswell_gazebo" "roswell_moveit_config" "roswell_navigation" "moveit_python" "simple_grasping" "teleop_twist_keyboard")
set(roswell_gazebo_demo_BUILDTOOL_DEPENDS "catkin")
set(roswell_gazebo_demo_BUILDTOOL_EXPORT_DEPENDS )
set(roswell_gazebo_demo_EXEC_DEPENDS "actionlib" "roswell_gazebo" "roswell_moveit_config" "roswell_navigation" "moveit_python" "simple_grasping" "teleop_twist_keyboard")
set(roswell_gazebo_demo_RUN_DEPENDS "actionlib" "roswell_gazebo" "roswell_moveit_config" "roswell_navigation" "moveit_python" "simple_grasping" "teleop_twist_keyboard")
set(roswell_gazebo_demo_TEST_DEPENDS )
set(roswell_gazebo_demo_DOC_DEPENDS )
set(roswell_gazebo_demo_DEPRECATED "")